### PR TITLE
Documentation updates per f2f with Russ

### PR DESCRIPTION
**Pull request by sherm1**
@edrumwri, PTAL:
- modified the Initialize() documentation in simulator.h
- modified discrete_systems.h to throw more shade on 2(b)

---
This change is [Reviewable](https://reviewable.io/reviews/edrumwri/drake/16)

### CODE REVIEW

**Review by edrumwri — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/16)* status: all files reviewed, 5 unresolved discussions (waiting on @sherm1)

___
*[systems/discrete_systems.h, line 134 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdaE1H-T8TXSeHoZgL:-LTdaE1H-T8TXSeHoZgM:b-3dkm65) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L134)):*
> ```objc
> `t=n*h` where h is a periodic sampling time. In Figure 1 we've shown the
> conversion to time used by the example above as a second horizontal axis,
> assuming h=0.02 seconds.
> ```

I think you want a line break after this.
___
*[systems/discrete_systems.h, line 170 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdaLV9ACeTTFstv5Su:-LTdaLVADgGzGsYMQxrz:b-z4zzyo) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L170)):*
> ```objc
> 
> Although you might expect that 2(b) is the most natural mapping from the
> discrete system to a continuous one, in practice it is problematic for mixed
> ```

Nit: suggest turning this sentence into two (it's three clauses)
___
*[systems/discrete_systems.h, line 171 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdaYhe3AIZbjyb5uQR:-LTdaYhe3AIZbjyb5uQS:bnmnen1) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L171)):*
> ```objc
> Although you might expect that 2(b) is the most natural mapping from the
> discrete system to a continuous one, in practice it is problematic for mixed
> discrete/continuous (hybrid) systems so Drake uses the mapping in 2(a). The
> ```

When you say "Drake uses the mapping", it sounds baked-in. In reality, it's the individual discrete systems (presumably primitives and other building blocks), and there is no requirement that they do one or the other.
___
*[systems/discrete_systems.h, line 174 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdasIA22nSrMRwTneb:-LTdasIA22nSrMRwTnec:b-47ukz2) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L174)):*
> ```objc
> advantage of 2(a) is that the hybrid update function `xₙ₊₁ = f(t,n,xₙ,u(t))`
> is invoked at time `t=n*h`, while in 2(b) it would be invoked at time
> `t=(n+1)*h`. That would make it difficult to coordinate discrete and continuous
> ```

This statement about difficulty might be true, but I don't see why that would be the case. If you look at the sinusoidal system, I had to do some manipulations because t was always a period behind. That is a direct consequence of doing things "the Drake way".
___
*[systems/discrete_systems.h, line 179 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdbUgJ6Igi1K2MroYM:-LTdbUgK7VmgrJyEqQKi:bijm8i2) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L179)):*
> ```objc
> Drake's choice of 2(a) dictates what value a discrete quantity will have when
> evaluated at times _between_ update times. In particular, a discrete variable
> x has value `x(t) = xₙ` for `t ∈ ((n-1)*h, n*h]`. You can see that clearly
> ```

This implies that there is only a discrete value at each point in time. We know this not to be true.

**Review by sherm1 — COMMENTED** [review]
Ready for another look.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/16#-:-LTdt10CB0EmlkZ-E81K:b467oqh)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @edrumwri)

___
*[systems/discrete_systems.h, line 134 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdaE1H-T8TXSeHoZgL:-LTdkBOh023_JBoB7sLS:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L134)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I think you want a line break after this.
</blockquote></details>

Done.
___
*[systems/discrete_systems.h, line 170 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdaLV9ACeTTFstv5Su:-LTdkuGe2nriEOZh2oh5:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L170)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit: suggest turning this sentence into two (it's three clauses)
</blockquote></details>

Done.
___
*[systems/discrete_systems.h, line 171 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdaYhe3AIZbjyb5uQR:-LTdkxTy7VeJ_VQLoHED:bsjvws9) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L171)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

When you say "Drake uses the mapping", it sounds baked-in. In reality, it's the individual discrete systems (presumably primitives and other building blocks), and there is no requirement that they do one or the other.
</blockquote></details>

I think Russ's point was that this really is baked in. Per that discussion, the documentation here now acknowledges only 2(a) as something Drake supports. As long as you make the equivalence `t=n*h` 2(a) is your only choice because of where we put the event handler invocations.
___
*[systems/discrete_systems.h, line 174 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdasIA22nSrMRwTneb:-LTdqjf_1bIHi_9cwnql:bd9jake) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L174)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This statement about difficulty might be true, but I don't see why that would be the case. If you look at the sinusoidal system, I had to do some manipulations because t was always a period behind. That is a direct consequence of doing things "the Drake way".
</blockquote></details>

I don't think it was behind at all -- step n was sampled at `t=n*h` just as it says here for 2(a). I think if you reword that example to express time as nh it will match what's here.
___
*[systems/discrete_systems.h, line 179 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdbUgJ6Igi1K2MroYM:-LTdsoim3mQPQMpGSjNU:b-cj38sb) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L179)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

This implies that there is only a discrete value at each point in time. We know this not to be true.
</blockquote></details>

Done. Good point, ptal.

**Review by edrumwri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/16)* status: all files reviewed, 2 unresolved discussions (waiting on @sherm1)

___
*[systems/discrete_systems.h, line 171 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdaYhe3AIZbjyb5uQR:-LTduFWO2oIfBp6eYfYY:bcf6eol) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L171)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I think Russ's point was that this really is baked in. Per that discussion, the documentation here now acknowledges only 2(a) as something Drake supports. As long as you make the equivalence `t=n*h` 2(a) is your only choice because of where we put the event handler invocations.
</blockquote></details>

It doesn't seem baked in because anyone can write a system that does the first update at h. I'd be okay with clarifying that "Drake does it this way" means that we do this in all of our primitive systems for consistency, not that this is somehow enforced.
___
*[systems/discrete_systems.h, line 174 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdasIA22nSrMRwTneb:-LTdtZN32hduU-xKYU7U:boww2ih) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L174)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I don't think it was behind at all -- step n was sampled at `t=n*h` just as it says here for 2(a). I think if you reword that example to express time as nh it will match what's here.
</blockquote></details>

Remember when I said yesterday, "the test isn't passing"? That was because I was testing the output from the signal logger, which was both time and state. I expected the signal logger data to produce sin(t*frequency), which it was not doing. It was always a period behind.

**Review by sherm1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/16)* status: all files reviewed, 2 unresolved discussions (waiting on @edrumwri)

___
*[systems/discrete_systems.h, line 171 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdaYhe3AIZbjyb5uQR:-LTeBd4LBG9E2Wex3gGw:bfr6azt) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L171)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

It doesn't seem baked in because anyone can write a system that does the first update at h. I'd be okay with clarifying that "Drake does it this way" means that we do this in all of our primitive systems for consistency, not that this is somehow enforced.
</blockquote></details>

But then you wouldn't be able to say `t=n*h`. Anyway, Russ wasn't claiming people couldn't do odd things, just that there is no point talking about them as though they were on an equal footing when there is a clear "n" to deal with. Is there something you want to say here that won't upset Russ? I would advocate we just tell people how it's done and let the very, very advanced folks figure out they can play other tricks if they want.
___
*[systems/discrete_systems.h, line 174 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdasIA22nSrMRwTneb:-LTeCjXp7wHPXQhBXAsa:bqluwd5) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L174)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Remember when I said yesterday, "the test isn't passing"? That was because I was testing the output from the signal logger, which was both time and state. I expected the signal logger data to produce sin(t*frequency), which it was not doing. It was always a period behind.
</blockquote></details>

After investigation, I realize this is a _delay_ system -- it's whole job in life is to delay the input signal by one step. _That's_ why it was a period behind -- because it was working perfectly! Good job!

**Review by edrumwri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/16)* status: all files reviewed, 1 unresolved discussion (waiting on @sherm1)

___
*[systems/discrete_systems.h, line 171 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdaYhe3AIZbjyb5uQR:-LTeDeDW9G7z_BT2uhPM:b-4ixzbu) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L171)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

But then you wouldn't be able to say `t=n*h`. Anyway, Russ wasn't claiming people couldn't do odd things, just that there is no point talking about them as though they were on an equal footing when there is a clear "n" to deal with. Is there something you want to say here that won't upset Russ? I would advocate we just tell people how it's done and let the very, very advanced folks figure out they can play other tricks if they want.
</blockquote></details>

Ok, I realize your trying to walk a tightrope between trying to make me happy and Russ happy. I'll retract my comment and see whether he bites.
___
*[systems/discrete_systems.h, line 174 at r1](https://reviewable.io/reviews/edrumwri/drake/16#-LTdasIA22nSrMRwTneb:-LTeDVzF6t-LVPrjbnqY:b-6uaep6) ([raw file](https://github.com/edrumwri/drake/blob/a5d9177d443d5b6ad84d9bd163fba67d9e9b65d3/systems/discrete_systems.h#L174)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

After investigation, I realize this is a _delay_ system -- it's whole job in life is to delay the input signal by one step. _That's_ why it was a period behind -- because it was working perfectly! Good job!
</blockquote></details>

I don't know that that's what Russ intended, but the test is there and does what he asks for :)

**Review by edrumwri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/16)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
