### PR TITLE
Sherm qdot2v doc

### PR DESCRIPTION
**Pull request by sherm1**
First crack at updated doc for the qdot_to_v stuff in `QuaternionFloatingJoint`. This includes a merge with upstream so will probably be a mess until you do an upstream merge into `rb_qdot_to_avel_fix2` branch. The only significant changes are in `quaternion_floating_joint.h` and they are not done.

---
This change is [Reviewable](https://reviewable.io/reviews/edrumwri/drake/2)

### CODE REVIEW

**Comment by edrumwri** [comment]
Review status: 0 of 633 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 30 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMSY5RGu4rL7FNTo3m:-KbMSY5RGu4rL7FNTo3n:b-9ws8sj) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L30)):*
> ```objc
>  *          px py pz   qw qx qy qz
>  * </pre>
>  * where `p_PB_P` is the position vector from P's origin Po to B's origin Bo,
> ```

Sherm, how did you arrive at this information on p_PB_P and q_PB? 

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 43 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMT0tsuZJ5XrvJmFvE:-KbMT0tsuZJ5XrvJmFvF:ba1iee0) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L43)):*
> ```objc
>  *          --------- -------------  7×1
>  * </pre>
>  * where `v_PB_P = d_P/dt p_PB_P` is the velocity of point Bo measured and
> ```

Bo is the center-of-mass of the child body?

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 55 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMTGiGeFzL-a3pa53s:-KbMTGiHe-9SNKjEfxxT:b-pkl5f3) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L55)):*
> ```objc
>  * </pre>
>  * where `ω_PB_B` is B's angular velocity in P, expressed in the B basis, and
>  * `v_PB_B` is point Bo's translational velocity in P, expressed in B.
> ```

Is there a functional difference between "expressed in the B basis" and "expressed in B"?

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 72 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMTVdeWdWJgBQ9D1D2:-KbMTVdeWdWJgBQ9D1D3:b6p0s9h) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L72)):*
> ```objc
>  * taken in the B frame, so this is *not* the acceleration of Bo in P. That
>  * acceleration is given by `a_PB_B = vdot_PB_B + ω_PB_B × v_PB_B` (still in B).
>  * Re-expressing that in P provides the configuration second derivative
> ```

"Re-expressing that acceleration in P"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/drake/2)*

**Comment by sherm1** [comment]
Addressed review comments, PTAL.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 30 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMSY5RGu4rL7FNTo3m:-KbMYojUTgONtyJ-2PSs:b2obfhb) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L30)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Sherm, how did you arrive at this information on p_PB_P and q_PB? 
</blockquote></details>

I got this from Paul's documentation in his cylinder test case.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 43 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMT0tsuZJ5XrvJmFvE:-KbMYvBWJe-1Zqc_A1pn:blpfcf2) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L43)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Bo is the center-of-mass of the child body?
</blockquote></details>

No, Bo is the origin point of the B frame (B sub O). Bcm is our notation for "com of body B".

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 55 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMTGiGeFzL-a3pa53s:-KbMZ9XWfIo7uA-Ed2Kv:b-60debt) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L55)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Is there a functional difference between "expressed in the B basis" and "expressed in B"?
</blockquote></details>

Done. No, one is just pedantic. Changed to "expressed in B".

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 72 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMTVdeWdWJgBQ9D1D2:-KbMZlV9eEOIuu3lA41V:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L72)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

"Re-expressing that acceleration in P"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/drake/2#-:-KbM_BNQNCZkQwBy2Dpu:b-ok9n27)*

**Comment by edrumwri** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 30 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMSY5RGu4rL7FNTo3m:-KbM_k4OXnoBW6MUXkPn:b-n8ao7n) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L30)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I got this from Paul's documentation in his cylinder test case.
</blockquote></details>

(without looking at Paul's test case) What is the likelihood that it passes Paul's test according to his documentation but is still wrong? Put another way: are all of the vectors involved in the frame offset non-zero, so that that aspect is stressed?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/drake/2)*

**Comment by sherm1** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[drake/multibody/joints/quaternion_floating_joint.h, line 30 at r1](https://reviewable.io:443/reviews/edrumwri/drake/2#-KbMSY5RGu4rL7FNTo3m:-KbMhc8B2d0j-MIcWmND:b-xmbbz9) ([raw file](https://github.com/edrumwri/drake/blob/44633b7a8e6697a95548f3f39b0b88d856387734/drake/multibody/joints/quaternion_floating_joint.h#L30)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

(without looking at Paul's test case) What is the likelihood that it passes Paul's test according to his documentation but is still wrong? Put another way: are all of the vectors involved in the frame offset non-zero, so that that aspect is stressed?
</blockquote></details>

Done. Per f2f: Paul's test has non-zero xyz and velocity values so should fail traumatically if we get the point wrong.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/drake/2)*

**Comment by edrumwri** [comment]
Reviewed 1 of 635 files at r1, 1 of 21 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edrumwri/drake/2)*

**Pull request merged**
