### PR TITLE
Updated discrete systems doc, added unit test for the doc example.

### PR DESCRIPTION
**Pull request by sherm1**
@edrumwri, here is a second PR that is possibly more controversial. I reworked the discrete_systems.h documentation following your outline, but 
- updated and simplified the pedagogical example as much as I could (given the missing sugar -- #10098),
- updated the notation to match the fibonacci example
- replaced all the external figures with much-simplified ascii-and-unicode graphs that read fine in the header and are easily modified and verified against the text, and
- shortened the text to focus as much as possible on Drake-specific issues -- I think it covers the same material but in a minimalist fashion.

I also added a unit test that is cut-and-paste from the pedagogical example to verify that it doesn't have typos and continues to work properly.

Please take a look at the header and generated doxygen and let me know what you think.

---
This change is [Reviewable](https://reviewable.io/reviews/edrumwri/drake/8)

### CODE REVIEW

**Review by edrumwri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/8)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @sherm1)

___
*[systems/discrete_systems.h, line 20 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQVRgABh9qNPKeGTIT:-LSQVRgB9c1O_ke90ZpC:bggodrj) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L20)):*
> ```objc
> state variable ("discrete" refers to the countability of the elements of the
> sequence, x₀, x₁, ..., xₙ and not the values that x can take), y is the desired
> output, u is an external input, and p is a set of (constant) parameters. f(.)
> ```

I specifically avoided "set" initially, since it has both math and C++ denotations and we do not intend either. 
___
*[systems/discrete_systems.h, line 69 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQX2Pu7GV7SXjWYqKF:-LSQX2Pv6DzYZwEJw9sL:bdyct8) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L69)):*
> ```objc
> 
>   // Set initial condition x₀ = 0.
>   void Initialize(systems::Context<double>* context_0) const {
> ```

Nit Naming this `context_0` (and the other, below, `context_n`) is a bit weird. Is there precedent for it?
___
*[systems/discrete_systems.h, line 132 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQa-zNA2XvdfeaLryT:-LSQa-zNA2XvdfeaLryU:ba3mqc3) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L132)):*
> ```objc
> 
> Drake's simulator is for hybrid systems, that is, systems that advance through
> _time_ and contain both continuous and discrete elements. It is easy enough to
> ```

Why "elements" here instead of the more specific "state"?
___
*[systems/discrete_systems.h, line 134 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQbTgt8jogTw3En5Pb:-LSQbTgt8jogTw3En5Pc:bwt3x15) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L134)):*
> ```objc
> _time_ and contain both continuous and discrete elements. It is easy enough to
> use time to represent the discrete steps n, by the conversion `t=n*h` where h
> is a periodic sampling time. If Figure 1 we've shown the conversion to time
> ```

Nit "If" -> "In"
___
*[systems/discrete_systems.h, line 136 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQb_KH2G59f9wA7FDo:-LSQb_KH2G59f9wA7FDp:brgotkg) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L136)):*
> ```objc
> is a periodic sampling time. If Figure 1 we've shown the conversion to time
> used by the example above as a second horizontal axis. However, since Drake
> simulations are continuous, it must be possible to obtain the values of all
> ```

"simulations are continuous" is not meaningful. Suggest "simulations allow interactions between discrete and continuous systems" 
___
*[systems/discrete_systems.h, line 152 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQc1hw50qSxbCAE2on:-LSQc1hw50qSxbCAE2oo:b-trprwq) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L152)):*
> ```objc
>      30 |         +━━━━●                    30 |              ●━
>         |         ┆                            |              ┆
>      20 |    +━━━━●                         20 |         ●━━━━+
> ```

Are you trying to convey something using the +'s here? I don't think you are and I do think you want a character like 🞅 or ∘ instead to show which value is sampled at a particular point in time.
___
*[systems/discrete_systems.h, line 171 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQeDW8C51Wake3g02b:-LSQeDW8C51Wake3g02c:b1tbbnr) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L171)):*
> ```objc
> the first events to occur at t=0 as we did in the example above. With that
> method the update that advances the discrete system from step n to step n+1
> occurs at time `t=n*h` as expected, allowing continuous values like u(t) to
> ```

Please consider renaming `t` slightly here because writing u(t) looks like you're calling u(.) out as a continuous function rather than evaluating it at a particular time. Perhaps just use u(nh) here.
___
*[systems/discrete_systems.h, line 174 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQfufhDVhZRhuJdSVY:-LSQfufhDVhZRhuJdSVZ:berl94a) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L174)):*
> ```objc
> be used in the update function. On the other hand, with the sampling in
> Figure 2(b) that update occurs at time `t=(n+1)*h` instead, meaning that the
> value u(t) would not be available unless it had been previously sampled.
> ```

How would it have been previously sampled? I'd prefer to say that the value here is u((n-1)h).
___
*[systems/discrete_systems.h, line 188 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQgDph4xPoB3GzbUxD:-LSQgDph4xPoB3GzbUxE:b-vjfsot) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L188)):*
> ```objc
> You can think of tᵢ⁻ as the time at the end of the iᵗʰ time step, while you can
> think of tᵢ⁺ as the time at the beginning of time step i+1. Initialization can
> be consider the 0ᵗʰ "time step", so t₀⁻ occurs at the end of initialization,
> ```

Nit "be considered"

**Review by edrumwri — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/8)* status: all files reviewed, 9 unresolved discussions (waiting on @sherm1)

**Review by sherm1 — COMMENTED** [review]
Responses below. Still to come:
- a "spike" unit tests per Russ's request
- possibly some tweaks to the Simulator doc

Since we agreed the missing initial publish was a bug fix, I'll hand this back to you for addressing the CI problems since that's in the original scope. Likely they are depending on the Simulator::publish_on_initialization() stuff which should now mostly get turned off. 

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/8#-:-LSRDs5E3OL3BRLEJ3xG:b-t2ixaz)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @edrumwri)

___
*[systems/discrete_systems.h, line 20 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQVRgABh9qNPKeGTIT:-LSQjxhQ3XA2MtkmbEhE:b-mzq9mg) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L20)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I specifically avoided "set" initially, since it has both math and C++ denotations and we do not intend either. 
</blockquote></details>

Done. Removed altogether as not relevant here and never mentioned again.
___
*[systems/discrete_systems.h, line 69 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQX2Pu7GV7SXjWYqKF:-LSQkCv5-42kj0LdJ7bI:bdkk7yj) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L69)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit Naming this `context_0` (and the other, below, `context_n`) is a bit weird. Is there precedent for it?
</blockquote></details>

I did this in the fibonacci example too, but I don't think I ever said anything about it. My intention was to mark the context with the  step number that the context's contents represent, like contextₙ analogous to how we're marking the states and outpus like xₙ. I'd be happy to remove that notation from here and fibonacci if you think it's not helpful.
___
*[systems/discrete_systems.h, line 132 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQa-zNA2XvdfeaLryT:-LSQktO2CMNi0BvljD1b:b-2dez9d) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L132)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why "elements" here instead of the more specific "state"?
</blockquote></details>

Elements is more general. For example, the bouncing ball hybrid system has nothing you could call a "discrete state" and in fact that's not a meaningful concept in general -- discrete vs continuous is a property of the update scheme, not the state variables. (See issue #9191)
___
*[systems/discrete_systems.h, line 134 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQbTgt8jogTw3En5Pb:-LSQlYPmAlnJVA48QBVB:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L134)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit "If" -> "In"
</blockquote></details>

Done.
___
*[systems/discrete_systems.h, line 136 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQb_KH2G59f9wA7FDo:-LSQm4qC9MsVxHNwSTPW:bvrrz8j) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L136)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

"simulations are continuous" is not meaningful. Suggest "simulations allow interactions between discrete and continuous systems" 
</blockquote></details>

Done. Your suggestion isn't what I was trying to say -- reworded, PTAL.
___
*[systems/discrete_systems.h, line 152 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQc1hw50qSxbCAE2on:-LSQnJoi38N1iKD0yE59:beyb8xc) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L152)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Are you trying to convey something using the +'s here? I don't think you are and I do think you want a character like 🞅 or ∘ instead to show which value is sampled at a particular point in time.
</blockquote></details>

Done -- ooh, that's so much nicer, thanks! I had to rework the text below also. Now I''m using the hollow circles to represent the t⁻ values and the solid ones to represent t⁺.
___
*[systems/discrete_systems.h, line 171 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQeDW8C51Wake3g02b:-LSRD7uI3JmfT7DWNEmw:b34q9dg) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L171)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Please consider renaming `t` slightly here because writing u(t) looks like you're calling u(.) out as a continuous function rather than evaluating it at a particular time. Perhaps just use u(nh) here.
</blockquote></details>

Done. I do want to emphasize the continuous nature of u here, without necessarily calling it a function. Switched to fuzzier "quantity". Below where I'm referring to a paricular value I used u(nh) as you suggested. 
___
*[systems/discrete_systems.h, line 174 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQfufhDVhZRhuJdSVY:-LSRDSd3EMl1UGnSd_qI:bfdmcx0) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L174)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

How would it have been previously sampled? I'd prefer to say that the value here is u((n-1)h).
</blockquote></details>

Done, ptal.
___
*[systems/discrete_systems.h, line 188 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQgDph4xPoB3GzbUxD:-LSRDV6J7Iv2lI9V7sz0:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L188)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit "be considered"
</blockquote></details>

Done.

**Review by edrumwri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/8)* status: all files reviewed, 5 unresolved discussions (waiting on @sherm1)

___
*[systems/discrete_systems.h, line 69 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQX2Pu7GV7SXjWYqKF:-LSREr3-5EFLIPiq-Sl9:b-8rar68) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L69)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

I did this in the fibonacci example too, but I don't think I ever said anything about it. My intention was to mark the context with the  step number that the context's contents represent, like contextₙ analogous to how we're marking the states and outpus like xₙ. I'd be happy to remove that notation from here and fibonacci if you think it's not helpful.
</blockquote></details>

Yeah, I don't think it adds much and it doesn't match with our common use in Drake (`context`).
___
*[systems/discrete_systems.h, line 132 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQa-zNA2XvdfeaLryT:-LSRIZ6V5FTLs99NRJS1:bvu4ag9) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L132)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Elements is more general. For example, the bouncing ball hybrid system has nothing you could call a "discrete state" and in fact that's not a meaningful concept in general -- discrete vs continuous is a property of the update scheme, not the state variables. (See issue #9191)
</blockquote></details>

Per f2f, I suggest "and evolve both continuously (flow) and discretely (jump) in time."
___
*[systems/discrete_systems.h, line 152 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQc1hw50qSxbCAE2on:-LSRKVN48xl_1f5gRyNu:b-83sjoh) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L152)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Done -- ooh, that's so much nicer, thanks! I had to rework the text below also. Now I''m using the hollow circles to represent the t⁻ values and the solid ones to represent t⁺.
</blockquote></details>

Nice!
___
*[systems/discrete_systems.h, line 165 at r2](https://reviewable.io/reviews/edrumwri/drake/8#-LSRK_URAy1BYvQbmB0i:-LSRK_URAy1BYvQbmB0j:b-muen0s) ([raw file](https://github.com/edrumwri/drake/blob/e1f743262ccd4a580863e4469986cb4b31c5ce8c/systems/discrete_systems.h#L165)):*
> ```objc
> In the figure, the ○ markers show the function value at time t _before_ the
> update function is invoked, while the ● markers show the value _after_ the
> update. In (a), the ○ markers coincide with the original discrete value, while
> ```

Nit "value" -> "values"
___
*[systems/discrete_systems.h, line 166 at r2](https://reviewable.io/reviews/edrumwri/drake/8#-LSRN4dkBNDtoLzabcv9:-LSRKr9fAzu9zcA1oS2c:bjb8bhc) ([raw file](https://github.com/edrumwri/drake/blob/e1f743262ccd4a580863e4469986cb4b31c5ce8c/systems/discrete_systems.h#L166)):*
> ```objc
> update function is invoked, while the ● markers show the value _after_ the
> update. In (a), the ○ markers coincide with the original discrete value, while
> in (b), the ● markers do. Thus both functions include the discrete result at
> ```

Per f2f, I don't know what you're trying to say with this sentence. I think it can be eliminated.

**Review by sherm1 — COMMENTED** [review]
All comments addressed, ptal. "Spike" unit test added.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/8#-:-LSRrMBZB8jZ87eYY7fL:biknplu)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @edrumwri)

___
*[systems/discrete_systems.h, line 69 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQX2Pu7GV7SXjWYqKF:-LSRnjzw7Rg_5UhA-yH_:b-1ecped) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L69)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Yeah, I don't think it adds much and it doesn't match with our common use in Drake (`context`).
</blockquote></details>

Done. Removed from here & fibonacci example.
___
*[systems/discrete_systems.h, line 132 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQa-zNA2XvdfeaLryT:-LSRq_0E1A8mlak5BQgK:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L132)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Per f2f, I suggest "and evolve both continuously (flow) and discretely (jump) in time."
</blockquote></details>

Done.
___
*[systems/discrete_systems.h, line 152 at r1](https://reviewable.io/reviews/edrumwri/drake/8#-LSQc1hw50qSxbCAE2on:-LSRqd_a5oha20LKduhr:b-2muhaa) ([raw file](https://github.com/edrumwri/drake/blob/3b0ea6c3573ab86f67e57bac0c9264f778ee7dfb/systems/discrete_systems.h#L152)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nice!
</blockquote></details>

(you are blocking here)
___
*[systems/discrete_systems.h, line 165 at r2](https://reviewable.io/reviews/edrumwri/drake/8#-LSRK_URAy1BYvQbmB0i:-LSRqRcHCahuZT8fytEy:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/e1f743262ccd4a580863e4469986cb4b31c5ce8c/systems/discrete_systems.h#L165)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit "value" -> "values"
</blockquote></details>

Done.
___
*[systems/discrete_systems.h, line 166 at r2](https://reviewable.io/reviews/edrumwri/drake/8#-LSRN4dkBNDtoLzabcv9:-LSRqSeX46jGR8ia374w:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/e1f743262ccd4a580863e4469986cb4b31c5ce8c/systems/discrete_systems.h#L166)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Per f2f, I don't know what you're trying to say with this sentence. I think it can be eliminated.
</blockquote></details>

Done.

**Review by edrumwri — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
