### PR TITLE
Updated Step documentation and misc simulator.h reviewer comments

### PR DESCRIPTION
**Pull request by sherm1**
@edrumwri this should address all of Sean's documentation comments in simulator.h, along with some misc comments Jeremy put there.

PTAL and merge if you're happy.

---
This change is [Reviewable](https://reviewable.io/reviews/edrumwri/drake/10)

### CODE REVIEW

**Review by edrumwri — CHANGES_REQUESTED** [review]
I like the updated pseudocode.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10#-:-LTAMO0n1Eob8VETkiCa:b-esjqbi)* status: all files reviewed, 3 unresolved discussions (waiting on @sherm1)

___
*[systems/analysis/simulator.h, line 67 at r1](https://reviewable.io/reviews/edrumwri/drake/10#-LTAK0Mr6VTGKOdRsZ6g:-LTAK0Mr6VTGKOdRsZ6h:b-w8mnqh) ([raw file](https://github.com/edrumwri/drake/blob/60b5e8a386652e1fbceac1d46ec49f0b15f16eb0/systems/analysis/simulator.h#L67)):*
> ```objc
> understand the simulation details in order to attain the desired state behavior
> over time. This behavior is dependent on the ordering in which discrete events
> and continuous updates are processed. The basic issues and terminology are
> ```

Why specifically leave out the unrestricted updates that are relevant to hybrid systems?
___
*[systems/analysis/simulator.h, line 71 at r1](https://reviewable.io/reviews/edrumwri/drake/10#-LTAKWR5CkOEIGn1ANpw:-LTAKDIK6PTPBr4wN_0x:b-pyl81j) ([raw file](https://github.com/edrumwri/drake/blob/60b5e8a386652e1fbceac1d46ec49f0b15f16eb0/systems/analysis/simulator.h#L71)):*
> ```objc
> proceeding.
> 
> As mentioned in the referenced document, when a continuous-time system has
> ```

Can you cut down on the number of parentheticals here ("as mentioned in the referenced document", "when a continuous-time system hsa discrete events"), possibly by splitting into two sentences?
___
*[systems/analysis/simulator.h, line 455 at r1](https://reviewable.io/reviews/edrumwri/drake/10#-LTALf5f7yHNFy3EoBV0:-LTALf5f7yHNFy3EoBV1:bat7xvv) ([raw file](https://github.com/edrumwri/drake/blob/60b5e8a386652e1fbceac1d46ec49f0b15f16eb0/systems/analysis/simulator.h#L455)):*
> ```objc
>   bool IntegrateContinuousState(const T& next_publish_dt,
>                                 const T& next_update_dt,
>                                 const T& time_of_next_event,
> ```

Naming this "time of next event" is slightly misleading since it's the time of the next timed event. I don't think anyone would believe that is to be a witnessed event, but why not use `time_of_next_timed_event` (here and below)?

**Review by sherm1 — COMMENTED** [review]
Responded to your comments. There are also some new changes to respond to Russ in discrete_systems.h (and I fixed the ordering in the Module list). I stopped using the t- t+ symbols in discrete_systems.h to match the updated Step doc.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10#-:-LTAbk891xg6MqpdU0Bx:b-hau2fp)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @edrumwri)

___
*[systems/analysis/simulator.h, line 67 at r1](https://reviewable.io/reviews/edrumwri/drake/10#-LTAK0Mr6VTGKOdRsZ6g:-LTAbEt7Dfa7PgNMXDsD:b-5ohl3a) ([raw file](https://github.com/edrumwri/drake/blob/60b5e8a386652e1fbceac1d46ec49f0b15f16eb0/systems/analysis/simulator.h#L67)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Why specifically leave out the unrestricted updates that are relevant to hybrid systems?
</blockquote></details>

Done. I've been using "discrete events" to mean any "jump" updates, not just Drake's DiscreteUpdate method. I clarified that here.
___
*[systems/analysis/simulator.h, line 71 at r1](https://reviewable.io/reviews/edrumwri/drake/10#-LTAKWR5CkOEIGn1ANpw:-LTAbaTpDkkSi9P-9XXw:b-iibsqp) ([raw file](https://github.com/edrumwri/drake/blob/60b5e8a386652e1fbceac1d46ec49f0b15f16eb0/systems/analysis/simulator.h#L71)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Can you cut down on the number of parentheticals here ("as mentioned in the referenced document", "when a continuous-time system hsa discrete events"), possibly by splitting into two sentences?
</blockquote></details>

Done. Yes, that was a mess. Hopefully better now.
___
*[systems/analysis/simulator.h, line 455 at r1](https://reviewable.io/reviews/edrumwri/drake/10#-LTALf5f7yHNFy3EoBV0:-LTAbgpvEZdpOASjCR5i:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/60b5e8a386652e1fbceac1d46ec49f0b15f16eb0/systems/analysis/simulator.h#L455)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Naming this "time of next event" is slightly misleading since it's the time of the next timed event. I don't think anyone would believe that is to be a witnessed event, but why not use `time_of_next_timed_event` (here and below)?
</blockquote></details>

Done.

**Review by edrumwri — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10)* status: all files reviewed, 5 unresolved discussions (waiting on @edrumwri and @sherm1)

___
*[systems/discrete_systems.h, line 185 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAfCL41ixNF0OcL0Rw:-LTAfCL51UyhaA7e8_Sj:b-zfz5b1) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L185)):*
> ```objc
> 
> A discrete system viewed in continuous time does not have a unique value at its
> sample times. In Figure 2 the ○ and ● symbols show two possible values at the
> ```

BTW How about "In Figure 2, each pair of ○ and ● symbols shows two possible values at the same time."?
___
*[systems/discrete_systems.h, line 195 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAg5i12Ntbe3SR2oqr:-LTAg5i12Ntbe3SR2oqs:bsea8p4) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L195)):*
> ```objc
> 
> You can think of xᵢ⁻ as the state's value at the end of the iᵗʰ step, while
> xᵢ⁺ is the value at the beginning of step i+1. Initialization can then be
> ```

Assume that the offset is at time zero, as recommended above.

Then this numbering scheme gives us x0 for initial conditions, x1 for the first update (at time 0), x2 for the second update (at time 1). 

So I propose that you call the variable at the beginning of step i+1 xᵢ₊₁⁺. 

Also, it would seem helpful to point out that xᵢ⁻ = xᵢ₊₁⁺.
___
*[systems/discrete_systems.h, line 201 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAiWvyD1qoKapaYlMm:-LTAiWvz0ArvVw-C1Mik:b-damgl9) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L201)):*
> ```objc
> With those distinctions drawn, we can define Drake's state update behavior
> during a time step:
>  - `Publish` events at time t see x⁻(t), so if a publish handler evaluates an
> ```

BTW I think this is very helpful.
___
*[systems/discrete_systems.h, line 204 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjYKM2DUF9uxYhVVc:-LTAjYKM2DUF9uxYhVVd:bofgd5p) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L204)):*
> ```objc
>    input it sees u⁻(t). This occurs at the end of a step, ○ markers in Figure 2.
>  - `Discrete` events at time t also see x⁻(t) and u⁻(t), and produce
>    x⁺(t). This occurs at the start of the next step, ● markers in Figure 2.
> ```

You've got a comma splice there- intentional?
___
*[systems/discrete_systems.h, line 205 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAifDh47cUEMiZ6SV1:-LTAifDh47cUEMiZ6SV2:b-nnv27x) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L205)):*
> ```objc
>  - `Discrete` events at time t also see x⁻(t) and u⁻(t), and produce
>    x⁺(t). This occurs at the start of the next step, ● markers in Figure 2.
>    Unrestricted updates precede discrete updates.
> ```

BTW I'd tend to expect to see those on the plot as you're talking about these concepts. I suggest making it clear that "Unrestricted updates (not depicted on the plots) immediately precede discrete updates.
___
*[systems/discrete_systems.h, line 207 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjFuo62VEiNa6f72g:-LTAjFuo62VEiNa6f72h:bax4rj3) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L207)):*
> ```objc
>    Unrestricted updates precede discrete updates.
>  - `Continuous` update (numerical integration and time advancement) starts with
>    x⁺(t) so initial input evaluation yields u⁺(t). Then time and continuous
> ```

I don't understand what you're trying to tell me with "initial input evaluation yields u+(t)".
___
*[systems/discrete_systems.h, line 209 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjjEm9MKjBmf-po5N:-LTAjjEn1mGERqfL2Glp:b-lpdy1x) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L209)):*
> ```objc
>    x⁺(t) so initial input evaluation yields u⁺(t). Then time and continuous
>    state advance (possibly in small increments) while the discrete variables are
>    held constant at their x⁺(t) values. Input port evaluations at intermediate
> ```

BTW I'm longing for the distinction in state types that you used in Simulator here, because it would really be less dissonant to talk about holding them constant at their xd⁺(t) values.
___
*[systems/discrete_systems.h, line 210 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAkfntAViFPP_NmaZ6:-LTAkfntAViFPP_NmaZ7:b93iy9o) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L210)):*
> ```objc
>    state advance (possibly in small increments) while the discrete variables are
>    held constant at their x⁺(t) values. Input port evaluations at intermediate
>    times t' > t are calculated with the x⁺(t) discrete values and xc(t')
> ```

Oh but you're trying to sneak it in anyway!

**Review by sherm1 — COMMENTED** [review]
All comments addressed. A few lingering questions ...

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10#-:-LTB7qXg7IO-zoBgfuPu:b-rjwcei)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @edrumwri)

___
*[systems/discrete_systems.h, line 185 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAfCL41ixNF0OcL0Rw:-LTB5REV3HDfS4XRY4gT:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L185)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW How about "In Figure 2, each pair of ○ and ● symbols shows two possible values at the same time."?
</blockquote></details>

Done.
___
*[systems/discrete_systems.h, line 195 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAg5i12Ntbe3SR2oqr:-LTB5YaE47BVB7sD9uLu:by2212q) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L195)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Assume that the offset is at time zero, as recommended above.

Then this numbering scheme gives us x0 for initial conditions, x1 for the first update (at time 0), x2 for the second update (at time 1). 

So I propose that you call the variable at the beginning of step i+1 xᵢ₊₁⁺. 

Also, it would seem helpful to point out that xᵢ⁻ = xᵢ₊₁⁺.
</blockquote></details>

It's right the way it is (assuming you agree that the first step is step 1). In your example, x0=x₀⁻(t₀) is the state at the end of initialization. x₀⁺(t₀) is the state immediately after the update in step 1 -- can't call that x₁. x₁⁻(t₁) is the value at the _end_ of step 1.

Also it is not true that xᵢ⁻ = xᵢ₊₁⁺ or that xᵢ⁻ = xᵢ⁺. The minuses and pluses are always separated by a discrete update.
___
*[systems/discrete_systems.h, line 204 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjYKM2DUF9uxYhVVc:-LTB2O7Y0XdAqbYTFzfS:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L204)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

You've got a comma splice there- intentional?
</blockquote></details>

Done.
___
*[systems/discrete_systems.h, line 205 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAifDh47cUEMiZ6SV1:-LTB2RrA8EaNK3cCm08e:b-q0o60w) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L205)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW I'd tend to expect to see those on the plot as you're talking about these concepts. I suggest making it clear that "Unrestricted updates (not depicted on the plots) immediately precede discrete updates.
</blockquote></details>

"discrete updates" is a generic term of art for all "jump" updates. It does not mean literally the Drake api called DiscreteUpdate (vs. UnrestrictedUpdate). At least that's not what I'm trying to say. (Clarified elsewhere.) I think the distinction between those is only important when we start looking inside StepTo. The flavor of Russ's comments was that we were already "in the weeds" with unnecessary details so I'd like to keep those to a minimum. I'll expand on this if you think I should but I'm not seeing the benefit at the moment.
___
*[systems/discrete_systems.h, line 207 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjFuo62VEiNa6f72g:-LTB3B3hDKVeJKZ_7SQL:b-ze7axy) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L207)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I don't understand what you're trying to tell me with "initial input evaluation yields u+(t)".
</blockquote></details>

Russ also asked about what the input values would be at various points (and I believe he was confused so this needs to be explicit). What this means is that if someone overloaded CalcTimeDerivatives() so that they can integrate, that method is going to be fed a context containing t and x⁺(t). If they use that context to call EvalInputPort(), they are going to get back u⁺(t) since those are the ingredients that will be available as the input port evaluates the connected output port and so on. Do you think we should say more about that here?
___
*[systems/discrete_systems.h, line 209 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjjEm9MKjBmf-po5N:-LTB44TS12dVEP9OywW0:b-3zav1h) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L209)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW I'm longing for the distinction in state types that you used in Simulator here, because it would really be less dissonant to talk about holding them constant at their xd⁺(t) values.
</blockquote></details>

Done. I was going to say we shouldn't add more detail here but then I see your solid point below that I already broke out xc (had to!).
___
*[systems/discrete_systems.h, line 210 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAkfntAViFPP_NmaZ6:-LTB7lJOAdxbjP1JtvLN:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L210)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Oh but you're trying to sneak it in anyway!
</blockquote></details>

Done.

**Review by edrumwri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10)* status: all files reviewed, 2 unresolved discussions (waiting on @sherm1 and @edrumwri)

___
*[systems/discrete_systems.h, line 195 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAg5i12Ntbe3SR2oqr:-LTDQg6A6NqA8D82E85z:b-klrjdf) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L195)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

It's right the way it is (assuming you agree that the first step is step 1). In your example, x0=x₀⁻(t₀) is the state at the end of initialization. x₀⁺(t₀) is the state immediately after the update in step 1 -- can't call that x₁. x₁⁻(t₁) is the value at the _end_ of step 1.

Also it is not true that xᵢ⁻ = xᵢ₊₁⁺ or that xᵢ⁻ = xᵢ⁺. The minuses and pluses are always separated by a discrete update.
</blockquote></details>

Right, I'm confused and this paragraph spurred that confusion. When you say a "+ value is the value at the beginning of a step", that's clearly not true. It's only the value after an update is performed.

Labeling these variables with both times and iterates is hard to think about. I'd avoid it unless it's absolutely necessary.
___
*[systems/discrete_systems.h, line 205 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAifDh47cUEMiZ6SV1:-LTDPpY67eXaMx6UVJHw:b-s540pe) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L205)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

"discrete updates" is a generic term of art for all "jump" updates. It does not mean literally the Drake api called DiscreteUpdate (vs. UnrestrictedUpdate). At least that's not what I'm trying to say. (Clarified elsewhere.) I think the distinction between those is only important when we start looking inside StepTo. The flavor of Russ's comments was that we were already "in the weeds" with unnecessary details so I'd like to keep those to a minimum. I'll expand on this if you think I should but I'm not seeing the benefit at the moment.
</blockquote></details>

That's fine, but you mention the ordering here- "Unrestricted updates precede discrete updates", right after you've been describing the figure. This reader was wondering how that tied into the figure.

**Review by edrumwri — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10)* status: all files reviewed, 3 unresolved discussions (waiting on @sherm1)

___
*[systems/discrete_systems.h, line 207 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjFuo62VEiNa6f72g:-LTDdUOZ1GnsHPZzMKkC:b-1p0z0w) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L207)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Russ also asked about what the input values would be at various points (and I believe he was confused so this needs to be explicit). What this means is that if someone overloaded CalcTimeDerivatives() so that they can integrate, that method is going to be fed a context containing t and x⁺(t). If they use that context to call EvalInputPort(), they are going to get back u⁺(t) since those are the ingredients that will be available as the input port evaluates the connected output port and so on. Do you think we should say more about that here?
</blockquote></details>

The description in your response is not coming across in the current text. I see why you're saying "initial" but I was missing the context (that input evaluation may change as t advances). The way that I would address this is just to put a full stop after "starts with x⁺(t)". Then, I would say "Derivative evaluations at intermediate times t' > t are calculated using both those discrete values and input values u⁺(t')". 
___
*[systems/discrete_systems.h, line 191 at r3](https://reviewable.io/reviews/edrumwri/drake/10#-LTDeB8-06cGF2NpLiAg:-LTDeB8-06cGF2NpLiAh:bxmapiz) ([raw file](https://github.com/edrumwri/drake/blob/0e7abb738237d175c04612734f995bc884b8bb83/systems/discrete_systems.h#L191)):*
> ```objc
> variables are updated, and x⁺(t) the value of x at time t _after_ they are
> updated. Thus if we have `t = n*h` then `x⁻(t) = xₙ` and `x⁺(t) = xₙ₊₁`.
> Similarly, evaluating an input u(t) yields u⁻(t) before discrete updates, and
> ```

Up to this point, we've been focused on the state changing at an instant. We're expecting the reader to immediately grok that input can change with the update as well. What do you think of making that explicit?
___
*[systems/discrete_systems.h, line 213 at r3](https://reviewable.io/reviews/edrumwri/drake/10#-LTDfzC8305uFIr8CGLm:-LTDfzC8305uFIr8CGLn:b-cfwg43) ([raw file](https://github.com/edrumwri/drake/blob/0e7abb738237d175c04612734f995bc884b8bb83/systems/discrete_systems.h#L213)):*
> ```objc
>    (state partitions xd and xa) are held constant at their x⁺(t) values, that
>    is, at xd⁺(t) and xa⁺(t). Derivative and input port evaluations at
>    intermediate times t' > t are calculated those discrete values and
> ```

BTW "those" -> "using those"

**Review by sherm1 — COMMENTED** [review]
Great comments, thanks. PTAL.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10#-:-LTEVyZ25HRdkOXIXF9w:b-k7ea2k)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @edrumwri)

___
*[systems/discrete_systems.h, line 195 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAg5i12Ntbe3SR2oqr:-LTESD1U71FhGaH2uuvt:bzcokoh) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L195)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Right, I'm confused and this paragraph spurred that confusion. When you say a "+ value is the value at the beginning of a step", that's clearly not true. It's only the value after an update is performed.

Labeling these variables with both times and iterates is hard to think about. I'd avoid it unless it's absolutely necessary.

</blockquote></details>

Argggh! Your understanding of my notation is better than mine. I see now that you are right about the i and i+1 subscripts. Sorry for arguing about it! I've taken a crack now at making it correct and clearer, ptal. Also switched i back to n to help tie this paragraph to earlier discussion of discrete systems.
___
*[systems/discrete_systems.h, line 205 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAifDh47cUEMiZ6SV1:-LTEUMVU7Zfyeg_pDOhV:b7rt8w9) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L205)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

That's fine, but you mention the ordering here- "Unrestricted updates precede discrete updates", right after you've been describing the figure. This reader was wondering how that tied into the figure.
</blockquote></details>

Done. I think this is better, ptal.
___
*[systems/discrete_systems.h, line 207 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjFuo62VEiNa6f72g:-LTEUTy-8NkD3CKpvSR3:bk7c6lf) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L207)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

The description in your response is not coming across in the current text. I see why you're saying "initial" but I was missing the context (that input evaluation may change as t advances). The way that I would address this is just to put a full stop after "starts with x⁺(t)". Then, I would say "Derivative evaluations at intermediate times t' > t are calculated using both those discrete values and input values u⁺(t')". 
</blockquote></details>

Reworked, ptal.
___
*[systems/discrete_systems.h, line 191 at r3](https://reviewable.io/reviews/edrumwri/drake/10#-LTDeB8-06cGF2NpLiAg:-LTEP-p241kY-zNwN_N9:b-ydonir) ([raw file](https://github.com/edrumwri/drake/blob/0e7abb738237d175c04612734f995bc884b8bb83/systems/discrete_systems.h#L191)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Up to this point, we've been focused on the state changing at an instant. We're expecting the reader to immediately grok that input can change with the update as well. What do you think of making that explicit?
</blockquote></details>

Done. Good idea.
___
*[systems/discrete_systems.h, line 213 at r3](https://reviewable.io/reviews/edrumwri/drake/10#-LTDfzC8305uFIr8CGLm:-LTEUb4O23V72s3-3vfB:b-uwmnzj) ([raw file](https://github.com/edrumwri/drake/blob/0e7abb738237d175c04612734f995bc884b8bb83/systems/discrete_systems.h#L213)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

BTW "those" -> "using those"
</blockquote></details>

n/a now

**Review by edrumwri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10)* status: all files reviewed, 2 unresolved discussions (waiting on @sherm1)

___
*[systems/discrete_systems.h, line 195 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAg5i12Ntbe3SR2oqr:-LTEn75R7KMNmW-E7uh4:blyphgp) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L195)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Argggh! Your understanding of my notation is better than mine. I see now that you are right about the i and i+1 subscripts. Sorry for arguing about it! I've taken a crack now at making it correct and clearer, ptal. Also switched i back to n to help tie this paragraph to earlier discussion of discrete systems.
</blockquote></details>

No problem.
___
*[systems/discrete_systems.h, line 207 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjFuo62VEiNa6f72g:-LTEo1bK9Dm4I_FB85Uh:b-20p65k) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L207)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

Reworked, ptal.
</blockquote></details>

I actually liked when you called out u⁺, but I'm not going to block on its absence.
___
*[systems/discrete_systems.h, line 200 at r4](https://reviewable.io/reviews/edrumwri/drake/10#-LTEnB6t6cry9UedNexW:-LTEnB6t6cry9UedNexX:bszos07) ([raw file](https://github.com/edrumwri/drake/blob/d29efd7510f15a9645382dd8b54f6d2ef222a84a/systems/discrete_systems.h#L200)):*
> ```objc
> updates occur, yielding xₙ₊₁⁺, with time unchanged at tₙ. Initialization can
> be considered the 0ᵗʰ "step", so x₀⁻(t₀) is the state at the end of
> initialization, while x₁⁺(t₀) is the state just after the discrete updates at
> ```

Did you intentionally make "discrete updates" plural here?
___
*[systems/discrete_systems.h, line 213 at r4](https://reviewable.io/reviews/edrumwri/drake/10#-LTEnPpFC4PM0qhoRAU3:-LTEnPpFC4PM0qhoRAU4:b-ohykyg) ([raw file](https://github.com/edrumwri/drake/blob/d29efd7510f15a9645382dd8b54f6d2ef222a84a/systems/discrete_systems.h#L213)):*
> ```objc
>  - `Continuous` update (numerical integration and time advancement) starts with
>    x⁺(t). Input and derivative evaluations will occur repeatedly as the time
>    and continuous state advance and each evaluation will be performed using
> ```

Nit: you've got a run-on sentence here (and it leads to some mild ambiguity)- you just need a comma after "advance".

**Review by sherm1 — COMMENTED** [review]
Done. Added one question for you.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10#-:-LTEqkP59eudYnMoPF4Z:b-7y8vo3)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @edrumwri)

___
*[systems/discrete_systems.h, line 207 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjFuo62VEiNa6f72g:-LTEpbJe2Rs727sbt1M_:b-x14mss) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L207)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

I actually liked when you called out u⁺, but I'm not going to block on its absence.
</blockquote></details>

If I do that here now I would also need to introduce notation for time derivatives, like u⁺(t) and xc_dot⁺(t). I was happy to get rid of the t' and would rather not toss in any new notation here. 

One question: do we need to add the updating of u and xc during continuous integration to the StepTo doc in Simulator? (I hope not)
___
*[systems/discrete_systems.h, line 200 at r4](https://reviewable.io/reviews/edrumwri/drake/10#-LTEnB6t6cry9UedNexW:-LTEp-3y-NnYTXF1PvOZ:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/d29efd7510f15a9645382dd8b54f6d2ef222a84a/systems/discrete_systems.h#L200)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Did you intentionally make "discrete updates" plural here?
</blockquote></details>

Done.
___
*[systems/discrete_systems.h, line 213 at r4](https://reviewable.io/reviews/edrumwri/drake/10#-LTEnPpFC4PM0qhoRAU3:-LTEqWjqEzG1gmWMDLP9:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/d29efd7510f15a9645382dd8b54f6d2ef222a84a/systems/discrete_systems.h#L213)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit: you've got a run-on sentence here (and it leads to some mild ambiguity)- you just need a comma after "advance".
</blockquote></details>

Done.

**Review by edrumwri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @edrumwri)

___
*[systems/discrete_systems.h, line 207 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjFuo62VEiNa6f72g:-LTEsYi71_UUPqey2swj:bfzd1in) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L207)):*
<details><summary><i>Previously, sherm1 (Michael Sherman) wrote…</i></summary><blockquote>

If I do that here now I would also need to introduce notation for time derivatives, like u⁺(t) and xc_dot⁺(t). I was happy to get rid of the t' and would rather not toss in any new notation here. 

One question: do we need to add the updating of u and xc during continuous integration to the StepTo doc in Simulator? (I hope not)
</blockquote></details>

Strictly speaking, we don't have to since all input is most generally a function of state. But, yeah, a statement that which input an updating process (e.g., "continuous update") will see depends on what state partitions that input is a function of.

**Review by edrumwri — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by edrumwri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/10)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by sherm1** [comment]
___
*[systems/discrete_systems.h, line 207 at r2](https://reviewable.io/reviews/edrumwri/drake/10#-LTAjFuo62VEiNa6f72g:-LTEw7AW8ZWLXz_i0AbG:b3t6bgv) ([raw file](https://github.com/edrumwri/drake/blob/3258aa37a21343787dfd02b3ea72655dfec8530b/systems/discrete_systems.h#L207)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Strictly speaking, we don't have to since all input is most generally a function of state. But, yeah, a statement that which input an updating process (e.g., "continuous update") will see depends on what state partitions that input is a function of. 
</blockquote></details>

OK, I added a sentence addressing that in simulator.h, ptal.

**Pull request merged**
