### PR TITLE
Minor mods and terminology cleanup in Simulator doc

### PR DESCRIPTION
**Pull request by sherm1**
@edrumwri this is hopefully my final PR for this branch. Contents:
- some cleanup and terminology update in the Simulator stepping documentation
- removed the now-unused .png and .svg files
- fixed the Discrete Systems module title and cross-referenced from Simulator

PTAL!

---
This change is [Reviewable](https://reviewable.io/reviews/edrumwri/drake/9)

### CODE REVIEW

**Review by edrumwri — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/9)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @sherm1)

___
*[systems/analysis/simulator.h, line 68 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSVUpEcEh6lm6qPwV71:-LSVUpEh5Tb1cCGQ4hR5:b-8xb1ec) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L68)):*
> ```objc
> state behavior over time. This behavior is dependent on the ordering in
> which events are processed. For a general introduction, see
> @ref discrete_systems, for details keep reading here.
> ```

FYI comma splice "," -> ";"
___
*[systems/analysis/simulator.h, line 82 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSX-aTBEbKucNKEimAY:-LSX-aTBEbKucNKEimAZ:b-o2z63c) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L82)):*
> ```objc
> The pseudocode follows:
> ```
> // Advance time and state from t⁻ to a time t₁⁻, where t ≤ t₁ ≤ tₘₐₓ.
> ```

Per f2f, I can't get over thinking of an indefinite time t, rather than a definite one as you intended.
___
*[systems/analysis/simulator.h, line 93 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSVtYaODdfdIwu5qgMj:-LSVtYaODdfdIwu5qgMk:b-s6b3k1) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L93)):*
> ```objc
> 
>   // --------------------
>   // Context is now at t⁺
> ```

Nit We haven't said anything about a context, so I'd change "Context is" to "Time and state are" (here and below)
___
*[systems/analysis/simulator.h, line 122 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSWx_lPES2UM5priNUt:-LSWx_lPES2UM5priNUu:b4xx6l0) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L122)):*
> ```objc
>   t ← current_time
>   while t ≠ tₘₐₓ
>     { t, xc(t⁻), xd(t⁻), xa(t⁻) } ← Step(t, xc, xd, xa, tₘₐₓ)
> ```

Per f2f, I prefer the current version. Yes, it's more verbose, but there is never any doubt which quantities are being evaluated or how they are being updated.
___
*[systems/analysis/simulator.h, line 129 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSX18D346N96AS1H-rz:-LSX18D346N96AS1H-s-:bz418qp) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L129)):*
> ```objc
> procedure Initialize(t₀, xc₀, xd₀, xa₀)
>   { xc(t₀⁻), xd(t₀⁻), xa(t₀⁻) } ← DoAnyUpdates as in Step()
>   tₑᵥₑₙₜ ← CalcNextEventTime(t₀ - ε, xc(t₀⁻), xd(t₀⁻), xa(t₀⁻))  // ε ≪ 1
> ```

Per f2f, the computation of `tₑᵥₑₙₜ` appears to have no purpose.

**Review by sherm1 — COMMENTED** [review]
All review comments addressed, PTAL.

> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/9#-:-LSXHfPR56L_bE2XGX9U:bm90dc)* status: 1 of 9 files reviewed, 3 unresolved discussions (waiting on @edrumwri)

___
*[systems/analysis/simulator.h, line 68 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSVUpEcEh6lm6qPwV71:-LSXHcGP93FOscRyQfGA:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L68)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

FYI comma splice "," -> ";"
</blockquote></details>

Done.
___
*[systems/analysis/simulator.h, line 82 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSX-aTBEbKucNKEimAY:-LSXHFg92Mlw4S-WPY1i:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L82)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Per f2f, I can't get over thinking of an indefinite time t, rather than a definite one as you intended.
</blockquote></details>

Done.
___
*[systems/analysis/simulator.h, line 93 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSVtYaODdfdIwu5qgMj:-LSXH8qR3a2EHdhJs45E:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L93)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Nit We haven't said anything about a context, so I'd change "Context is" to "Time and state are" (here and below)
</blockquote></details>

Done.
___
*[systems/analysis/simulator.h, line 122 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSWx_lPES2UM5priNUt:-LSXHBAa2RqgbgCVQsF-:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L122)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Per f2f, I prefer the current version. Yes, it's more verbose, but there is never any doubt which quantities are being evaluated or how they are being updated.
</blockquote></details>

Done.
___
*[systems/analysis/simulator.h, line 129 at r1](https://reviewable.io/reviews/edrumwri/drake/9#-LSX18D346N96AS1H-rz:-LSXHCiN7dgArGtV_r0g:b-896fix) ([raw file](https://github.com/edrumwri/drake/blob/ee191f132243152006e432ac4fa857843031e141/systems/analysis/simulator.h#L129)):*
<details><summary><i>Previously, edrumwri (Evan Drumwright) wrote…</i></summary><blockquote>

Per f2f, the computation of `tₑᵥₑₙₜ` appears to have no purpose.
</blockquote></details>

Done.

**Review by edrumwri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/9)* status: 3 of 9 files reviewed, all discussions resolved

**Review by edrumwri — APPROVED** [review]
> Reviewed 6 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/edrumwri/drake/9)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
